name: sutils
description: "SUtils"
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  mime: ^1.0.6
  plugin_platform_interface: ^2.0.2
  shared_preferences: ^2.3.3
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.stronzlabs.sutils
        pluginClass: SUtilsPlugin
